services:
  - type: web
    name: cultrahus-sangam-2026
    runtime: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
